// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bubobubo.domain;

import com.bubobubo.domain.Roles;

privileged aspect Roles_Roo_JavaBean {
    
    public String Roles.getNameDa() {
        return this.nameDa;
    }
    
    public void Roles.setNameDa(String nameDa) {
        this.nameDa = nameDa;
    }
    
}
